/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BEP20 } from "./BEP20";
export * as factories from "./factories";
export { BEP20__factory } from "./factories/BEP20__factory";
